### PR TITLE
docs: add configuration info for flags not supported by inputs

### LINKED ISSUE #292: feat(input): add path to secret config file
## Description
Trivy has [config file](https://aquasecurity.github.io/trivy/v0.48/docs/references/configuration/config-file/) and [secret config file](https://aquasecurity.github.io/trivy/v0.48/docs/scanner/secret/#configuration), but `trivy-action` has input (`with` field) only for path to `config file`.
Is it possible to add input for path to `secret config file`?

## Related discussions
- https://github.com/aquasecurity/trivy/discussions/5824

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
There are flags not supported by [inputs](https://github.com/aquasecurity/trivy-action#inputs).
We need to write about ways to configure these flags by ENVs and config file.

## Related Issues
- Close #292

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
Are tests broken?
I changed only `README.MD` file.

**Comment by simar7** [comment]
> Are tests broken?
> I changed only `README.MD` file.

Yes they are. See https://github.com/aquasecurity/trivy-action/issues/294 for details.

Would you have some cycles to work on that by any chance? It would be nice to get them fixed.

**Review by simar7 — APPROVED** [review]
thanks for the PR, this looks great!

**Comment by DmitriyLewen** [comment]
> Yes they are. See https://github.com/aquasecurity/trivy-action/issues/294 for details.
Would you have some cycles to work on that by any chance? It would be nice to get them fixed.

I will write into this issue if i have time for it.

**Pull request merged**
