### PR TITLE
fix: 🐛 allow trivy-config and other options to be used together

### PR DESCRIPTION
**Pull request by arairyus**
resolved: #337 

## Summary

Allow trivy-config and other options to be used together.

### CODE REVIEW

**Review by simar7 — APPROVED** [review]
thanks!

**Comment by goatwu1993** [comment]
@arairyus quote break aquasecurity/trivy-action@master
```
/entrypoint.sh: line 212: unexpected EOF while looking for matching `"'
```

**Comment by arairyus** [comment]
sorry ...

**Comment by afdesk** [comment]
@arairyus could you recreate this PR?

**Pull request merged**
