### PR TITLE
chore: Update trivy version to 0.26.0

### PR DESCRIPTION
**Pull request by krol3**
- Update trivy version to 0.25.4
- add unit-test for the security-checks option

### CODE REVIEW

**Comment by simar7** [comment]
Would you know why this test is failing on your branch when run locally?

```
 trivy-action git:(trivy-0.25.3) bats -r .
 ✓ trivy image
 ✗ trivy image sarif report
   (in test file ./test/test.bats, line 13)
     `result="$(diff ./test/data/image-sarif.test image-sarif.test)"' failed
   Running trivy with options:  --format  sarif --severity  CRITICAL --output  image-sarif.test  knqyf263/vuln-image:1.2.3
   Global options:  
   2022-04-18T08:25:07.474-0700 INFO    Detected OS: alpine
   2022-04-18T08:25:07.474-0700 INFO    Detecting Alpine vulnerabilities...
   2022-04-18T08:25:07.475-0700 INFO    Number of language-specific files: 2
   2022-04-18T08:25:07.475-0700 INFO    Detecting cargo vulnerabilities...
   2022-04-18T08:25:07.476-0700 INFO    Detecting composer vulnerabilities...
   2022-04-18T08:25:07.477-0700 WARN    This OS version is no longer supported by the distribution: alpine 3.7.1
   2022-04-18T08:25:07.477-0700 WARN    The vulnerability detection may be insufficient because security updates are not provided
 ✓ trivy config
 ✓ trivy rootfs
 ✓ trivy fs
 ✓ trivy fs with securityChecks option
 ✓ trivy repo

7 tests, 1 failure
```

**Comment by krol3** [comment]
@simar7 what trivy version are you using ?

**Comment by simar7** [comment]
> @simar7 what trivy version are you using ?

works after the upgrade

**Review by simar7 — APPROVED** [review]

**Comment by krol3** [comment]
@knqyf263,   the version was upgraded to 0.26.0

**Comment by knqyf263** [comment]
Thanks

**Pull request merged**
