### PR TITLE
chore: Update trivy version to 0.26.0

### PR DESCRIPTION
**Pull request by afdesk**
Updating the version of Trivy image.

### CODE REVIEW

**Comment by knqyf263** [comment]
@simar7 @krol3 Could you test v0.26.0? It will contains notable changes and we should deliver it shortly.

**Comment by krol3** [comment]
@knqyf263  I tested the version 0.26.0 in my PR that it's opened with unit test. https://github.com/aquasecurity/trivy-action/pull/102

**Review by krol3 — COMMENTED** [review]
It's missing to change the version in the gh-test. Check this PR that I'm changing the version too. https://github.com/aquasecurity/trivy-action/pull/102

**Comment by afdesk** [comment]
@krol3 your PR is better. i closed it.

**Pull request closed without merging**
