### PR TITLE
Bump to ghcr.io/aquasecurity/trivy:0.35.0

### PR DESCRIPTION
**Pull request by tusharkshatriya**
Add 0.35.0 release.

### CODE REVIEW

**Comment by tusharkshatriya** [comment]
@simar7 Can I get a review please?

**Review by simar7 — APPROVED** [review]

**Comment by simar7** [comment]
looks like tests are failing

**Comment by tusharkshatriya** [comment]
Could you please help me understand what other changes are required for tests to pass?

**Review by JAORMX — APPROVED** [review]

**Comment by simar7** [comment]
> Could you please help me understand what other changes are required for tests to pass?

You can see the assertion failing https://github.com/aquasecurity/trivy-action/actions/runs/3737188503/jobs/6522631553

looks like the path you have in the golden file is incorrect

**Comment by flaxel** [comment]
What is the status of this PR? 🤔 It would be really cool to get this bump or better the new version `0.37.0` because there is a fix for a current trivy issue. 👍

**Comment by simar7** [comment]
Closing as abandoned in favour of https://github.com/aquasecurity/trivy-action/pull/199

**Pull request closed without merging**
