### PR TITLE
Add ability to pass --offline-scan

### PR DESCRIPTION
**Pull request by jdolitsky**
Want to use this to avoid any issues w/ Maven package scanning timing out (see https://github.com/aquasecurity/trivy/issues/3421)

### CODE REVIEW

**Comment by amandahla** [comment]
I did that by setting it in the config file.
https://aquasecurity.github.io/trivy/v0.36/docs/references/customization/config-file/#scan-options

**Comment by jdolitsky** [comment]
FYI - we have started using this fork within Chainguard since yesterday and have yet to see a timeout error

**Comment by simar7** [comment]
for newer options, we recommend using the trivy config file as mentioned earlier in the comments. I'll be closing this for now.

**Comment by yyvess** [comment]
As exemple if the action is used on a reusable workflow or an composite action.
On this case, when GitHub action run the Trivy docker, no volum are mount to the reusable workflow file then Trivy configuration cannot be reader...

**Pull request closed without merging**
