### PR TITLE
bump trivy to v0.42.0

### PR DESCRIPTION
**Pull request by danielchabr**
bump trivy to [v0.42.0](https://github.com/aquasecurity/trivy/releases/tag/v0.42.0)

### CODE REVIEW

**Comment by knqyf263** [comment]
@simar7 Can you please take a look?

**Comment by simar7** [comment]
It lgtm, but there's a failing test. Has the SARIF schema changed, @knqyf263?

**Comment by knqyf263** [comment]
Yes, we bumped the SARIF version.
https://github.com/aquasecurity/trivy/issues/3916

**Comment by danielchabr** [comment]
> Yes, we bumped the SARIF version. [aquasecurity/trivy#3916](https://github.com/aquasecurity/trivy/issues/3916)

I've updated the schema in those test files https://github.com/aquasecurity/trivy-action/pull/237/commits/212cc0ac9a1c826350d3eaa04b419ce343105558. Would you rerun the build?

**Comment by knqyf263** [comment]
I've rerun the build.

**Comment by simar7** [comment]
Thanks will take another look today.

**Review by simar7 — APPROVED** [review]
lgtm, thanks!!!

**Pull request merged**
