### PR TITLE
chore(deps): bump Trivy to v0.51.1

### PR DESCRIPTION
**Pull request by DmitriyLewen**
## Description
Bump Trivy to [v0.51.1](https://github.com/aquasecurity/trivy/releases/tag/v0.51.1)

### CODE REVIEW

**Comment by DmitriyLewen** [comment]
@simar7 Take a look, when you have time, please.

**Comment by simar7** [comment]
@DmitriyLewen Thanks for the PR but I'd like to have this [PR](https://github.com/aquasecurity/trivy-action/pull/334) merged first as it will really be great to have tests in place prior to making changes to Trivy Action. I believe @nikpivkin is almost finished with it and the PR will be merged soon.

**Comment by simar7** [comment]
@DmitriyLewen could you rebase on the latest main branch? I've merged the tests PR.

**Comment by simar7** [comment]
@DmitriyLewen I updated it here https://github.com/aquasecurity/trivy-action/pull/353 - we can close this PR

**Pull request closed without merging**
