### PR TITLE
chore: Update Trivy to 0.40.0

### PR DESCRIPTION
**Pull request by PerfectSlayer**
Bumps Trivy to [v0.40.0](https://github.com/aquasecurity/trivy/releases/tag/v0.40.0) and update tests data.

### CODE REVIEW

**Comment by arxeiss** [comment]
Would be nice to update to v0.40.0 and then merge.

**Comment by PerfectSlayer** [comment]
> Would be nice to update to v0.40.0 and then merge.

Done. But I am stuck waiting for a review.

**Comment by simar7** [comment]
Thanks will take a look at it.

**Comment by simar7** [comment]
@PerfectSlayer can you fix the tests?

**Comment by PerfectSlayer** [comment]
@simar7 I fixed the two remaining tests.

**Review by simar7 — APPROVED** [review]
thanks very much!

**Pull request merged**
