### PR TITLE
Update to Latest Release of Trivy :) 

### PR DESCRIPTION
**Pull request by NickLiffen**
Update to Latest Release of Trivy :)

### CODE REVIEW

**Comment by NickLiffen** [comment]
@simar7 would love your thoughts on this ❤️

**Comment by simar7** [comment]
@krol3 could you take a look?

**Review by krol3 — APPROVED** [review]
The image is successfully built.

**Comment by NickLiffen** [comment]
Thanks, @krol3 :) If you could merge and release that would be amazing ❤️

**Review by simar7 — APPROVED** [review]
thanks lgtm!

**Comment by krol3** [comment]
I tested the new version using this rep: https://github.com/krol3/demo-trivy/runs/4337332773

**Pull request merged**
