### PR TITLE
feat(#59) add support to skip files

### LINKED ISSUE #59: Add support to skip-files
While the already implemented in the GitHub-action `skip-dirs` does the job it feels not natural to use for files.

Since Trivy already support `--skip-files`, it would be nice to support it also on the GitHub action.

I could implement the feature if you feel valuable.

### PR DESCRIPTION
**Pull request by gustavomonarin**
closes #59

### CODE REVIEW

**Comment by dannyibishev** [comment]
@gustavomonarin are you able to sign the license to get this unblocked? I'd also very much like to use this feature :)

**Comment by neil-hickey** [comment]
hey @dannyibishev / @gustavomonarin any idea when this might be included in trivy-action? This is something I was looking for also

**Comment by simar7** [comment]
@krol3 could you take a look?

**Review by simar7 — APPROVED** [review]
lgtm thanks!

**Pull request merged**
